Lint/NotNil:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# exclude all files in vendor/cache
Globs:
  - "**/*.cr"
  - "!vendor"
  - "!lib"
