#!/bin/bash

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "${BLUE}🚗 starting acceptance test suite...${OFF}"

COMPOSE_FILE="$DIR/spec/acceptance/docker-compose.acceptance.yml"

# bring down the stack if it is running
docker compose -f $COMPOSE_FILE down --remove-orphans -v -t 1

# prime the acceptance test suite
crystal run --debug --error-trace $DIR/spec/acceptance/primer.cr

# start the stack
docker compose -f $COMPOSE_FILE up --build -d

echo "\n"
crystal run --debug --error-trace $DIR/spec/acceptance/acceptance.cr
