#!/bin/bash

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "${BLUE}🚗 starting acceptance test suite...${OFF}"

COMPOSE_FILE="$DIR/acceptance/docker-compose.acceptance.yml"

# bring down the stack if it is running
docker compose -f $COMPOSE_FILE down --remove-orphans -v -t 1

# prime the acceptance test suite
crystal run --debug --error-trace $DIR/acceptance/primer.cr

# start the stack
docker compose -f $COMPOSE_FILE up --build -d

# debugging if LOG_LEVEL is set to DEBUG
if [ "$LOG_LEVEL" == "DEBUG" ]; then
  sleep 3
  docker compose -f $COMPOSE_FILE ps
  docker compose -f $COMPOSE_FILE logs

  ls -lah $DIR/acceptance/logs
fi

# wait for all artifacts to be created before continuing
crystal run --debug --error-trace $DIR/acceptance/wait-for-artifacts.cr

# bring the stack down now that the artifacts are created
docker compose -f $COMPOSE_FILE down --remove-orphans -v -t 1

# run the acceptance test suite
crystal run --debug --error-trace $DIR/acceptance/acceptance.cr
