#!/bin/bash

set -e

source script/setup-env $@

if [[ "$CI" == "true" ]]; then
  source script/ci-env
fi

echo -e "🧹 ${BLUE}formatting ${PURPLE}crystal${BLUE} files...${OFF}"

crystal tool format $@

echo -e "✅ ${GREEN}formatting complete!${OFF}"
