#!/bin/bash

set -e

source script/setup-env $@

if [[ "$CI" == "true" ]]; then
  source script/ci-env
fi

echo -e "🖌️  ${BLUE}linting ${PURPLE}crystal${BLUE} files..."

"$DIR/bin/ameba" $@

echo -e "✅ ${GREEN}linting complete!${OFF}"
