#!/bin/bash

set -e

source script/setup-env "$@"

if [[ "$CI" == "true" ]]; then
  source script/ci-env
fi

mkdir -p "$DIR/bin"

flags="$@"

if [[ "$flags" == *"--ci"* ]]; then
  echo $OSTYPE
  echo $(uname -m)
fi

# Determine the vendor bin directory for this platform
os="unknown"
arch="unknown"
vendor_bin_dir=""
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  os="linux"
  vendor_bin_dir="$LINUX_VENDOR_DIR"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  os="mac"
  arch=$(uname -m)
  if [ "$arch" = "x86_64" ]; then
    vendor_bin_dir="$DARWIN_VENDOR_DIR_X64"
  elif [ "$arch" = "arm64" ]; then
    vendor_bin_dir="$DARWIN_VENDOR_DIR_ARM64"
  else
    echo "Unknown architecture: $arch"
  fi
else
  os="unknown"
fi

if [ -n "$vendor_bin_dir" ] && [ -d "$vendor_bin_dir" ]; then
  if [[ "$flags" == *"--ci"* ]]; then
    echo "OSTYPE: $OSTYPE"
    echo "ARCH: $arch"
    echo "running in CI mode, copying vendored binaries to bin/ directory ($os)"
  else
    echo "copying vendored binaries to bin/ directory ($os)"
  fi
  cp -r "$vendor_bin_dir/." "$DIR/bin"
fi

if [[ ! "$@" == *"--production"* ]]; then
  # ensure the ameba binary is built and available in the bin directory
  AMEBA_UP_TO_DATE=false
  # first, check the version of the ameba binary in the lock file
  AMEBA_VERSION=$(SHARDS_INSTALL_PATH="$SHARDS_INSTALL_PATH" $SHARDS_BIN list | grep ameba | awk '{print $3}' | tr -d '()')

  # if the bin/ameba binary exists, check if it is the correct version
  if [ -f "$DIR/bin/ameba" ]; then
    CURRENT_VERSION=$("$DIR/bin/ameba" --version)
    if [ "$AMEBA_VERSION" = "$CURRENT_VERSION" ]; then
      AMEBA_UP_TO_DATE=true
    else
      echo "ameba binary is not up to date"
      echo "ameba version (./bin/ameba): $CURRENT_VERSION"
      echo "ameba version (shards list): $AMEBA_VERSION"
      AMEBA_UP_TO_DATE=false
    fi
  fi

  if [ "$AMEBA_UP_TO_DATE" = false ] && [ -n "$vendor_bin_dir" ] && [ -f "$vendor_bin_dir/ameba" ]; then
    VENDORED_AMEBA_VERSION=$("$vendor_bin_dir/ameba" --version 2>/dev/null || true)
    if [ "$AMEBA_VERSION" = "$VENDORED_AMEBA_VERSION" ]; then
      echo "using vendored ameba binary"
      cp "$vendor_bin_dir/ameba" "$DIR/bin/ameba"
      AMEBA_UP_TO_DATE=true
    fi
  fi

  if [ "$AMEBA_UP_TO_DATE" = false ]; then
    echo "building ameba binary"
    (
      cd "$SHARDS_INSTALL_PATH/ameba"
      $SHARDS_BIN build
    )
    cp "$SHARDS_INSTALL_PATH/ameba/bin/ameba" "$DIR/bin/ameba"
  fi
fi
