#!/bin/bash

set -e

source script/setup-env $@

# if the script was invoked with the --dev flag, run the development version
if [ "$1" == "--dev" ]; then

  LOG_LEVEL="DEBUG"
  if [ "$2" == "--log-level" ]; then
    LOG_LEVEL="$3"
  fi

  shards run --debug --error-trace -- -c config.yml --log-level $LOG_LEVEL
else
  shards run --release --debug --error-trace
fi
