#!/bin/bash

set -e

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "🧪 ${BLUE}running unit tests...${OFF}"

if [ ! -f "$DIR/bin/kcov" ]; then
  echo "WARN: the kcov binary cannot be found at $DIR/bin/kcov - no code coverage report will be generated"
  crystal spec
else
  $DIR/bin/crkcov --cleanup-coverage-before --coverage-dir $DIR/coverage --fail-below-low 100 --kcov-executable $DIR/bin/kcov
fi

echo -e "✅ ${GREEN}tests complete!${OFF}"
