#!/bin/bash

set -e

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "🧪 ${BLUE}running unit tests...${OFF}"

os="unknown"
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  os="linux"
elif [[ "$OSTYPE" == "darwin"* ]]; then
  os="mac"
fi

skip_coverage=false
for arg in "$@"; do
  if [ "$arg" == "-s" ]; then
    skip_coverage=true
    break
  fi
done

# if -s was supplied as an argument, skip coverage reports (they can be slow)
if $skip_coverage; then
  crystal spec
elif [ "$os" == "mac" ]; then
  # on mac, code coverage isn't working for a reason I couldn't fix
  crystal spec
# if the kcov binary cannot be found, warn and run specs without coverage
elif [ ! -f "$DIR/bin/kcov" ]; then
  echo "WARN: the kcov binary cannot be found at $DIR/bin/kcov - no code coverage report will be generated"
  crystal spec
# otherwise, run specs with coverage
else
  $DIR/bin/crkcov --cleanup-coverage-before --coverage-dir $DIR/coverage --kcov-executable $DIR/bin/kcov --output
fi

echo -e "✅ ${GREEN}tests complete!${OFF}"
