name: acceptance

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  acceptance:
    name: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: fetch crystal version
        id: crystal-version
        run: echo "crystal=$(cat .crystal-version)" >> $GITHUB_OUTPUT

      - name: install crystal
        uses: crystal-lang/install-crystal@v1.8.2
        with:
          crystal: ${{ steps.crystal-version.outputs.crystal }}

      - name: bootstrap
        run: script/bootstrap --ci

      - name: set directory permissions (for ci)
        run: |
          chmod -R 777 ./acceptance
          chmod 700 ./acceptance/ssh_server/keys
          chmod 600 ./acceptance/ssh_server/keys/private/id_rsa
          chmod 600 ./acceptance/ssh_server/keys/public/id_rsa.pub

      - name: acceptance
        env:
          LOG_LEVEL: DEBUG
          CRYSTAL_ENV: development
        run: script/acceptance
