name: acceptance

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  acceptance:
    name: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - name: fetch crystal version
        id: crystal-version
        run: echo "crystal=$(cat .crystal-version)" >> $GITHUB_OUTPUT

      - name: install crystal
        uses: crystal-lang/install-crystal@d8ef131ecec0352ce0e39b81b0a6d95def58fe2f # pin@v1.9.2
        with:
          crystal: ${{ steps.crystal-version.outputs.crystal }}

      - name: bootstrap
        run: script/bootstrap --ci

      - name: set directory permissions (for ci)
        run: |
          chmod -R 777 ./acceptance
          chmod 700 ./acceptance/ssh_server/keys
          chmod 600 ./acceptance/ssh_server/keys/private/id_rsa
          chmod 600 ./acceptance/ssh_server/keys/public/id_rsa.pub

      - name: acceptance
        env:
          LOG_LEVEL: DEBUG
          CRYSTAL_ENV: development
        run: script/acceptance
