name: docker

on:
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".dockerignore"
      - ".github/workflows/docker.yml"
      - "acceptance/Dockerfile"
      - "acceptance/docker-compose.acceptance.yml"
      - "acceptance/ssh_server/Dockerfile"
      - ".crystal-version"
      - "shard.yml"
      - "shard.lock"
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker:
    name: docker
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: extract image metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # pin@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=sha

      - name: set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # pin@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # pin@v3.3.0

      - name: login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # pin@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        id: push
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # pin@v6.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: digest
        env:
          DIGEST: ${{ steps.push.outputs.digest }}
        run: |
          echo "digest: $DIGEST"

      # - name: generate artifact attestation
      #   uses: actions/attest-build-provenance@v1.3.2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: ${{ github.event_name != 'pull_request' }}
