name: release
on:
  push:
    branches: [main]
    paths: ["src/version.cr"]
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: fetch crystal version
        id: crystal-version
        run: echo "crystal=$(cat .crystal-version)" >> $GITHUB_OUTPUT

      - name: install crystal
        uses: crystal-lang/install-crystal@56684e85b94c6340f5035965d57dcfdedd1ab0de # pin@v1.9.1
        with:
          crystal: ${{ steps.crystal-version.outputs.crystal }}

      - name: bootstrap
        run: script/bootstrap --ci

      - name: fetch version
        run: |
          export RELEASE_VERSION=$(grep -o 'v[0-9]\+\.[0-9]\+\.[0-9]\+' src/version.cr)
          echo "VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

      - name: test
        run: script/test

      - name: build (linux x86_64)
        run: |
          mkdir -p releases
          script/build --production
          mv ./bin/runway ./releases/runway-linux-x86_64

      - name: generate artifact attestation
        uses: actions/attest-build-provenance@00014ed6ed5efc5b1ab7f7f34a39eb55d41aa4f8 # pin@v3.1.0
        with:
          subject-path: 'releases/runway-*'
      
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # pin@v6
        with:
          name: runway-binaries
          path: releases/

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # pin@v2.2.1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Push a Release
        id: release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # pin@v1.20.0
        with:
          artifacts: "./releases/*"
          tag: ${{ env.VERSION }}
          generateReleaseNotes: true
          artifactErrorsFailBuild: true
          replacesArtifacts: true
          token: ${{ steps.app-token.outputs.token }}

      - name: release url
        env:
          RELEASE_URL: ${{ steps.release.outputs.html_url }}
        run: |
          echo "release url: $RELEASE_URL"
