name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6
        with:
          persist-credentials: false

      - name: fetch crystal version
        id: crystal-version
        run: echo "crystal=$(cat .crystal-version)" >> $GITHUB_OUTPUT

      - name: install crystal
        uses: crystal-lang/install-crystal@56684e85b94c6340f5035965d57dcfdedd1ab0de # pin@v1.9.1
        with:
          crystal: ${{ steps.crystal-version.outputs.crystal }}

      - name: bootstrap
        run: script/bootstrap --ci

      - name: test
        run: script/test
